"""
Export Manager for Stimme - handles exporting translations to various formats
"""

import os
import json
import markdown
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any, Optional

class ExportManager:
    """Manages exporting translations to various formats"""
    
    def __init__(self, export_dir: str = None):
        self.export_dir = export_dir or os.path.join(os.getcwd(), "exports")
        self.ensure_export_dir()
    
    def ensure_export_dir(self):
        """Ensure export directory exists"""
        os.makedirs(self.export_dir, exist_ok=True)
    
    def set_export_directory(self, directory: str):
        """Set the export directory"""
        self.export_dir = directory
        self.ensure_export_dir()
    
    def get_export_directory(self) -> str:
        """Get the current export directory"""
        return self.export_dir
    
    def export_translation_txt(
        self, 
        source_text: str, 
        translation: str, 
        commentary: str = None,
        metadata: Dict[str, Any] = None,
        filename: str = None
    ) -> str:
        """
        Export translation to plain text format
        
        Returns:
            Path to the exported file
        """
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            # Create safe filename from first few words of source
            safe_source = "".join(c for c in source_text[:30] if c.isalnum() or c in (' ', '-', '_')).strip()
            safe_source = safe_source.replace(' ', '_')
            filename = f"translation_{safe_source}_{timestamp}.txt"
        
        filepath = os.path.join(self.export_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            # Header
            f.write("=" * 60 + "\n")
            f.write("STIMME TRANSLATION EXPORT\n")
            f.write("=" * 60 + "\n\n")
            
            # Metadata
            if metadata:
                f.write("METADATA:\n")
                f.write("-" * 20 + "\n")
                f.write(f"Export Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write(f"Model: {metadata.get('model_used', 'Unknown')}\n")
                if metadata.get('translation_time'):
                    f.write(f"Translation Time: {metadata['translation_time']:.2f}s\n")
                f.write("\n")
            
            # Source text
            f.write("GERMAN SOURCE:\n")
            f.write("-" * 20 + "\n")
            f.write(source_text.strip() + "\n\n")
            
            # Translation
            f.write("ENGLISH TRANSLATION:\n")
            f.write("-" * 20 + "\n")
            f.write(translation.strip() + "\n\n")
            
            # Commentary if available
            if commentary:
                f.write("PHILOLOGICAL COMMENTARY:\n")
                f.write("-" * 20 + "\n")
                # Convert markdown to plain text (basic conversion)
                plain_commentary = self._markdown_to_plain_text(commentary)
                f.write(plain_commentary.strip() + "\n\n")
            
            # Footer
            f.write("=" * 60 + "\n")
            f.write("Generated by Stimme - Scholarly German Translation Tool\n")
            f.write("=" * 60 + "\n")
        
        return filepath
    
    def export_translation_html(
        self, 
        source_text: str, 
        translation: str, 
        commentary: str = None,
        metadata: Dict[str, Any] = None,
        filename: str = None
    ) -> str:
        """
        Export translation to HTML format with styling
        
        Returns:
            Path to the exported file
        """
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            safe_source = "".join(c for c in source_text[:30] if c.isalnum() or c in (' ', '-', '_')).strip()
            safe_source = safe_source.replace(' ', '_')
            filename = f"translation_{safe_source}_{timestamp}.html"
        
        filepath = os.path.join(self.export_dir, filename)
        
        # Use the existing formatter
        try:
            from formatter import get_styled_html
            html_content = get_styled_html(translation, commentary)
        except ImportError:
            # Fallback HTML generation
            html_content = self._generate_html(source_text, translation, commentary, metadata)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return filepath
    
    def export_translation_markdown(
        self, 
        source_text: str, 
        translation: str, 
        commentary: str = None,
        metadata: Dict[str, Any] = None,
        filename: str = None
    ) -> str:
        """
        Export translation to Markdown format
        
        Returns:
            Path to the exported file
        """
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            safe_source = "".join(c for c in source_text[:30] if c.isalnum() or c in (' ', '-', '_')).strip()
            safe_source = safe_source.replace(' ', '_')
            filename = f"translation_{safe_source}_{timestamp}.md"
        
        filepath = os.path.join(self.export_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            # Header
            f.write("# Stimme Translation Export\n\n")
            
            # Metadata
            if metadata:
                f.write("## Metadata\n\n")
                f.write(f"- **Export Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write(f"- **Model**: {metadata.get('model_used', 'Unknown')}\n")
                if metadata.get('translation_time'):
                    f.write(f"- **Translation Time**: {metadata['translation_time']:.2f}s\n")
                f.write("\n")
            
            # Source text
            f.write("## German Source\n\n")
            f.write(f"> {source_text.strip()}\n\n")
            
            # Translation
            f.write("## English Translation\n\n")
            f.write(f"{translation.strip()}\n\n")
            
            # Commentary if available
            if commentary:
                f.write("## Philological Commentary\n\n")
                f.write(f"{commentary.strip()}\n\n")
            
            # Footer
            f.write("---\n")
            f.write("*Generated by Stimme - Scholarly German Translation Tool*\n")
        
        return filepath
    
    def export_multiple_translations(
        self, 
        translations: List[Dict[str, Any]], 
        format_type: str = "txt",
        filename: str = None
    ) -> str:
        """
        Export multiple translations to a single file
        
        Args:
            translations: List of translation dictionaries
            format_type: Export format ('txt', 'html', 'markdown')
            filename: Optional custom filename
            
        Returns:
            Path to the exported file
        """
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"stimme_translations_{timestamp}.{format_type}"
        
        filepath = os.path.join(self.export_dir, filename)
        
        if format_type == "txt":
            self._export_multiple_txt(translations, filepath)
        elif format_type == "html":
            self._export_multiple_html(translations, filepath)
        elif format_type == "markdown":
            self._export_multiple_markdown(translations, filepath)
        else:
            raise ValueError(f"Unsupported format: {format_type}")
        
        return filepath
    
    def _export_multiple_txt(self, translations: List[Dict[str, Any]], filepath: str):
        """Export multiple translations to TXT format"""
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write("=" * 80 + "\n")
            f.write("STIMME TRANSLATION COLLECTION\n")
            f.write("=" * 80 + "\n")
            f.write(f"Exported: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"Total Translations: {len(translations)}\n")
            f.write("=" * 80 + "\n\n")
            
            for i, trans in enumerate(translations, 1):
                f.write(f"TRANSLATION #{i}\n")
                f.write("-" * 40 + "\n")
                
                # Metadata
                if trans.get('timestamp'):
                    f.write(f"Date: {trans['timestamp'].strftime('%Y-%m-%d %H:%M:%S')}\n")
                if trans.get('metrics', {}).get('model_used'):
                    f.write(f"Model: {trans['metrics']['model_used']}\n")
                f.write("\n")
                
                # Source
                f.write("German Source:\n")
                f.write(f"{trans['source_full']}\n\n")
                
                # Translation
                f.write("English Translation:\n")
                f.write(f"{trans['translation']}\n\n")
                
                # Commentary
                if trans.get('commentary'):
                    f.write("Commentary:\n")
                    plain_commentary = self._markdown_to_plain_text(trans['commentary'])
                    f.write(f"{plain_commentary}\n\n")
                
                f.write("-" * 40 + "\n\n")
            
            f.write("=" * 80 + "\n")
            f.write("End of Collection\n")
            f.write("=" * 80 + "\n")
    
    def _export_multiple_markdown(self, translations: List[Dict[str, Any]], filepath: str):
        """Export multiple translations to Markdown format"""
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write("# Stimme Translation Collection\n\n")
            f.write(f"**Exported**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  \n")
            f.write(f"**Total Translations**: {len(translations)}\n\n")
            f.write("---\n\n")
            
            for i, trans in enumerate(translations, 1):
                f.write(f"## Translation #{i}\n\n")
                
                # Metadata
                if trans.get('timestamp') or trans.get('metrics', {}).get('model_used'):
                    f.write("**Metadata:**\n")
                    if trans.get('timestamp'):
                        f.write(f"- Date: {trans['timestamp'].strftime('%Y-%m-%d %H:%M:%S')}\n")
                    if trans.get('metrics', {}).get('model_used'):
                        f.write(f"- Model: {trans['metrics']['model_used']}\n")
                    f.write("\n")
                
                # Source
                f.write("### German Source\n\n")
                f.write(f"> {trans['source_full']}\n\n")
                
                # Translation
                f.write("### English Translation\n\n")
                f.write(f"{trans['translation']}\n\n")
                
                # Commentary
                if trans.get('commentary'):
                    f.write("### Commentary\n\n")
                    f.write(f"{trans['commentary']}\n\n")
                
                f.write("---\n\n")
            
            f.write("*Generated by Stimme - Scholarly German Translation Tool*\n")
    
    def _export_multiple_html(self, translations: List[Dict[str, Any]], filepath: str):
        """Export multiple translations to HTML format"""
        html_content = self._generate_collection_html(translations)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html_content)
    
    def _generate_html(self, source_text: str, translation: str, commentary: str = None, metadata: Dict[str, Any] = None) -> str:
        """Generate HTML content for a single translation"""
        html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stimme Translation Export</title>
    <style>
        body {
            font-family: 'Cormorant Garamond', Georgia, serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #2D232E;
            color: #E0DDCF;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #F1F0EA;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .section {
            margin-bottom: 30px;
        }
        .section-title {
            color: #F1F0EA;
            font-size: 1.3em;
            font-weight: bold;
            margin-bottom: 10px;
            border-bottom: 1px solid #534B52;
            padding-bottom: 5px;
        }
        .source {
            background-color: #38313A;
            padding: 20px;
            border-left: 4px solid #F1F0EA;
            font-style: italic;
        }
        .translation {
            background-color: #39323A;
            padding: 20px;
            border-radius: 5px;
        }
        .commentary {
            background-color: #433D42;
            padding: 20px;
            border-radius: 5px;
        }
        .metadata {
            font-size: 0.9em;
            color: #ACA49D;
            margin-bottom: 20px;
        }
        .footer {
            text-align: center;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #534B52;
            color: #ACA49D;
            font-size: 0.9em;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Stimme Translation Export</h1>
    </div>
"""
        
        if metadata:
            html += '<div class="metadata">'
            html += f'<strong>Export Date:</strong> {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}<br>'
            html += f'<strong>Model:</strong> {metadata.get("model_used", "Unknown")}<br>'
            if metadata.get('translation_time'):
                html += f'<strong>Translation Time:</strong> {metadata["translation_time"]:.2f}s<br>'
            html += '</div>'
        
        html += f'''
    <div class="section">
        <div class="section-title">German Source</div>
        <div class="source">{source_text}</div>
    </div>
    
    <div class="section">
        <div class="section-title">English Translation</div>
        <div class="translation">{translation}</div>
    </div>
'''
        
        if commentary:
            commentary_html = markdown.markdown(commentary, extensions=['extra'])
            html += f'''
    <div class="section">
        <div class="section-title">Philological Commentary</div>
        <div class="commentary">{commentary_html}</div>
    </div>
'''
        
        html += '''
    <div class="footer">
        Generated by Stimme - Scholarly German Translation Tool
    </div>
</body>
</html>'''
        
        return html
    
    def _generate_collection_html(self, translations: List[Dict[str, Any]]) -> str:
        """Generate HTML for multiple translations"""
        # Similar to single HTML but with multiple translations
        # Implementation would be similar to _generate_html but for collections
        pass  # Simplified for now
    
    def _markdown_to_plain_text(self, markdown_text: str) -> str:
        """Convert markdown to plain text (basic conversion)"""
        # Remove markdown formatting
        text = markdown_text
        # Remove headers
        text = text.replace('#', '')
        # Remove bold/italic
        text = text.replace('**', '').replace('*', '')
        # Remove links (basic)
        import re
        text = re.sub(r'\[([^\]]+)\]\([^\)]+\)', r'\1', text)
        return text.strip()
    
    def get_supported_formats(self) -> List[str]:
        """Get list of supported export formats"""
        return ['txt', 'html', 'markdown']